# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_collector', '0005_auto_20170808_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='be_client',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='be_host',
        ),
    ]
